name: "Gradle (Direct)"

"on":
  workflow_call:
    inputs:
      artifact:
        type: string
        default: "gradle-direct"
        description: "Artifact prefix"
      runner:
        default: "ubuntu-latest"
        type: string
        description: "Runner"
      java:
        default: "21"
        type: string
        description: "Java version"
      args:
        default: "--no-daemon --scan --no-configuration-cache --dependency-verification=lenient --warning-mode=none"
        type: string
        description: "Gradle arguments"
      build:
        default: "test integrationTest"
        type: string
        description: "Build target"
      run:
        default: "./run-with-gradle.sh"
        type: string
        description: "Run target"
      run_args:
        default: ""
        type: string
        description: "Runtime arguments"
      push:
        default: true
        type: boolean
        description: "Cache push"
    secrets:
      BUILDLESS_APIKEY:
        required: true
        description: "API key for build caching"

  workflow_dispatch:
    inputs:
      artifact:
        type: string
        default: "gradle-direct"
        description: "Artifact prefix"
      runner:
        default: "ubuntu-latest"
        description: "Runner"
      java:
        default: "21"
        description: "Java version"
      args:
        default: "--no-daemon --scan --no-configuration-cache --dependency-verification=lenient --warning-mode=none"
        type: string
        description: "Gradle arguments"
      build:
        default: "test integrationTest"
        type: string
        description: "Build target"
      run:
        default: "./run-with-gradle.sh"
        type: string
        description: "Run target"
      run_args:
        default: ""
        type: string
        description: "Runtime arguments"
      push:
        default: true
        type: boolean
        description: "Cache push"

permissions:
  contents: read
  packages: write

env:
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

jobs:
  build:
    name: "Gradle"
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: write
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: "Setup: Caches"
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        env:
          cache-name: caches-gradle
        with:
          path: |
            ~/.gradle
            ./.gradle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}-jvm${{ inputs.java }}
          # TODO: See discussion: https://github.com/jeremylong/DependencyCheck/issues/2560#issuecomment-702098748
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-jvm${{ inputs.java }}
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - name: "Setup: Java"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: ${{ inputs.java }}
      - name: "Setup: Buildless"
        uses: buildless/setup@30e82389418c7f17046606183bc4c78b2c8913e0 # v1.0.2
      - name: "Setup: Gradle"
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          gradle-version: release-candidate
          gradle-home-cache-cleanup: true
          dependency-graph: ${{ inputs.push && 'generate-and-submit' || 'generate' }}
      - name: "Build: Assemble and Test"
        run: |
          ./gradlew \
            ${{ inputs.args }} \
            ${{ inputs.build }}
      - name: "Build: Execute Run"
        env:
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
        run: ${{ inputs.run }} ${{ inputs.run_args }}
      - name: "Artifact: JARs"
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: ${{ inputs.artifact }}-jars
          path: build/libs/modern-java-practices*.jar
      - name: "Artifact: Reports"
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        if: always()
        with:
          name: ${{ inputs.artifact }}-reports
          path: |
            build/reports/*
            build/test-results/*
