name: "Push"

"on":
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'images/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  #
  # --- Builds: Direct ---
  #

  ## Gradle: Direct
  build-direct-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.direct.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: read
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: gradle-direct-jvm${{ matrix.java }}
      push: true  # push dependency graph up so it can be used for review
      coverage: true
      provenance: true

  ## Maven: Direct
  maven-direct-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.direct.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-direct-jvm${{ matrix.java }}

  #
  # --- Builds: Earthly ---
  #

  ## Gradle: Earthly
  build-earthly-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.earthly.yml
    secrets: inherit
    strategy:
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: gradle-earthly-jvm${{ matrix.java }}
      push: true

  ## Gradle: Earthly
  build-earthly-maven:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.earthly.yml
    secrets: inherit
    strategy:
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-earthly-jvm${{ matrix.java }}
      push: true

  #
  # --- Builds: Batect ---
  #

  ## Gradle: Batect
  build-batect-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.batect.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-gradle-jvm${{ matrix.java }}
      push: true

  ## Maven: Batect
  build-batect-maven:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.batect.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-batect-jvm${{ matrix.java }}
      push: true
