name: "Push"

"on":
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'images/**'

permissions:
  contents: read
  packages: write

jobs:
  #
  # --- Builds: Earthly ---
  #

  ## Gradle: Earthly
  build-earthly-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.earthly.yml
    secrets: inherit
    strategy:
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}

  ## Gradle: Earthly
  build-earthly-maven:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.earthly.yml
    secrets: inherit
    strategy:
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}

  #
  # --- Builds: Batect ---
  #

  # coming soon.

  #
  # --- Checks ---
  #

  ## Scan code with CodeQL.
  checks-codeql:
    name: "Checks"
    uses: ./.github/workflows/checks.codeql.yml
    permissions:
      contents: read
      actions: read
      security-events: write

  ## Scan dependencies for vulnerabilities.
  checks-scorecards:
    name: "Checks"
    uses: ./.github/workflows/checks.scorecards.yml
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
