name: "Pull Request"

"on":
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'

permissions:
  contents: read

jobs:
  #
  # --- Builds: Earthly ---
  #

  ## Gradle: Earthly
  build-earthly-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.earthly.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: gradle-earthly-jvm${{ matrix.java }}

  ## Maven: Earthly
  build-earthly-maven:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.earthly.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-earthly-jvm${{ matrix.java }}

  #
  # --- Builds: Batect ---
  #

  ## Gradle: Batect
  build-batect-gradle:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/gradle.batect.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: gradle-batect-jvm${{ matrix.java }}

  ## Maven: Batect
  build-batect-maven:
    name: "Build (Java ${{ matrix.java }})"
    uses: ./.github/workflows/maven.batect.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}
      artifact: maven-batect-jvm${{ matrix.java }}

  #
  # --- Checks ---
  #

  ## Scan code with CodeQL.
  checks-codeql:
    name: "Checks"
    uses: ./.github/workflows/checks.codeql.yml
    permissions:
      contents: read
      actions: read
      security-events: write

  ## Scan dependencies for vulnerabilities.
  checks-deps-review:
    name: "Checks"
    uses: ./.github/workflows/checks.dependency-review.yml
    permissions:
      contents: read
      pull-requests: write
      security-events: write
