name: "Pull Request"

"on":
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'

permissions:
  contents: read
  packages: write

jobs:
  #
  # --- Builds: Earthly ---
  #

  ## Gradle: Earthly
  build-earthly-gradle:
    name: "Build (Gradle)"
    uses: ./.github/workflows/gradle.earthly.yml
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    secrets: inherit
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}

  ## Gradle: Earthly
  build-earthly-maven:
    name: "Build (Maven)"
    uses: ./.github/workflows/maven.earthly.yml
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    secrets: inherit
    with:
      runner: ubuntu-latest
      java: ${{ matrix.java }}

  #
  # --- Builds: Batect ---
  #

  # coming soon.

  #
  # --- Checks ---
  #

  ## Scan code with CodeQL.
  checks-codeql:
    name: "Checks"
    uses: ./.github/workflows/checks.codeql.yml

  ## Scan dependencies for vulnerabilities.
  checks-deps-review:
    name: "Checks"
    uses: ./.github/workflows/checks.dependency-review.yml
